"""Templates module for OpenFOAM MCP."""

from .registry import (
    ParameterDefinition,
    CaseTemplate,
    TEMPLATES,
    PIPE_FLOW_TEMPLATE,
    CAVITY_FLOW_TEMPLATE,
    CYLINDER_FLOW_TEMPLATE,
    HEAT_TRANSFER_TEMPLATE,
    DAM_BREAK_TEMPLATE,
    BUBBLE_RISING_TEMPLATE,
    BACKWARD_STEP_TEMPLATE,
    CHANNEL_FLOW_TEMPLATE,
    HEAT_EXCHANGER_TEMPLATE,
    FLAT_PLATE_TEMPLATE,
    MIXING_ELBOW_TEMPLATE,
    SHOCK_TUBE_TEMPLATE,
    SUPERSONIC_NOZZLE_TEMPLATE,
    get_template,
    list_templates,
    get_template_summary,
)

__all__ = [
    "ParameterDefinition",
    "CaseTemplate",
    "TEMPLATES",
    "PIPE_FLOW_TEMPLATE",
    "CAVITY_FLOW_TEMPLATE",
    "CYLINDER_FLOW_TEMPLATE",
    "HEAT_TRANSFER_TEMPLATE",
    "DAM_BREAK_TEMPLATE",
    "BUBBLE_RISING_TEMPLATE",
    "BACKWARD_STEP_TEMPLATE",
    "CHANNEL_FLOW_TEMPLATE",
    "HEAT_EXCHANGER_TEMPLATE",
    "FLAT_PLATE_TEMPLATE",
    "MIXING_ELBOW_TEMPLATE",
    "SHOCK_TUBE_TEMPLATE",
    "SUPERSONIC_NOZZLE_TEMPLATE",
    "get_template",
    "list_templates",
    "get_template_summary",
]
