"""Knowledge base module for OpenFOAM MCP."""

from .solvers import (
    FlowType,
    TimeType,
    TurbulenceType,
    SolverInfo,
    SOLVERS,
    SOLVER_SELECTION_RULES,
    select_solver,
    estimate_reynolds_number,
    recommend_turbulence_model,
    get_solver_info,
    calculate_yplus_first_layer,
)

from .boundaries import (
    BoundaryType,
    InletType,
    OutletType,
    WallType,
    BoundaryCondition,
    BoundaryDefinition,
    BC_MAPPINGS,
    FLUID_PROPERTIES,
    get_boundary_conditions,
    get_fluid_properties,
    format_vector,
    format_scalar,
)

from .mesh_strategies import (
    MeshStrategy,
    GeometryType,
    MeshQualitySettings,
    MeshResolution,
    BlockMeshParams,
    RefinementRegion,
    AddLayersControls,
    SnappyHexMeshParams,
    calculate_mesh_resolution,
    select_mesh_strategy,
    create_pipe_mesh_params,
    create_cavity_mesh_params,
    create_external_flow_mesh_params,
    create_snappy_hex_mesh_params,
    estimate_cell_count,
    validate_mesh_quality,
    validate_snappy_params,
)

__all__ = [
    # Solvers
    "FlowType",
    "TimeType",
    "TurbulenceType",
    "SolverInfo",
    "SOLVERS",
    "SOLVER_SELECTION_RULES",
    "select_solver",
    "estimate_reynolds_number",
    "recommend_turbulence_model",
    "get_solver_info",
    "calculate_yplus_first_layer",
    # Boundaries
    "BoundaryType",
    "InletType",
    "OutletType",
    "WallType",
    "BoundaryCondition",
    "BoundaryDefinition",
    "BC_MAPPINGS",
    "FLUID_PROPERTIES",
    "get_boundary_conditions",
    "get_fluid_properties",
    "format_vector",
    "format_scalar",
    # Mesh
    "MeshStrategy",
    "GeometryType",
    "MeshQualitySettings",
    "MeshResolution",
    "BlockMeshParams",
    "RefinementRegion",
    "AddLayersControls",
    "SnappyHexMeshParams",
    "calculate_mesh_resolution",
    "select_mesh_strategy",
    "create_pipe_mesh_params",
    "create_cavity_mesh_params",
    "create_external_flow_mesh_params",
    "create_snappy_hex_mesh_params",
    "estimate_cell_count",
    "validate_mesh_quality",
    "validate_snappy_params",
]
