"""Tools module for OpenFOAM MCP."""

from .case_tools import (
    # Input models
    ListTemplatesInput,
    GetTemplateInfoInput,
    CreateCaseInput,
    ValidateCaseInput,
    RunSolverInput,
    GetRunStatusInput,
    AnalyzeProblemInput,
    GenerateMeshInput,
    GenerateBoundaryConditionsInput,
    RunParallelInput,
    GenerateResidualPlotInput,
    CalculateYplusInput,
    ResponseFormat,
    # Tool functions
    openfoam_list_templates,
    openfoam_get_template_info,
    openfoam_create_case,
    openfoam_validate_case,
    openfoam_run_solver,
    openfoam_analyze_problem,
    openfoam_get_fluid_properties,
    openfoam_generate_mesh,
    openfoam_generate_boundary_conditions,
    openfoam_get_run_status,
    openfoam_run_parallel,
    openfoam_generate_residual_plot,
    openfoam_calculate_yplus,
)
from .knowledge_tools import (
    SearchTutorialsInput,
    ReadTutorialFileInput,
    openfoam_search_tutorials,
    openfoam_read_tutorial_file,
)
from .debug_tools import (
    GetPatchListInput,
    ReadDictionaryInput,
    UpdateDictionaryInput,
    openfoam_get_patch_list,
    openfoam_read_dictionary,
    openfoam_update_dictionary,
)
from .stability_tools import (
    PreflightCheckInput,
    AssessCaseStabilityInput,
    ApplyStabilityFixesInput,
    openfoam_preflight_check,
    openfoam_assess_case_stability,
    openfoam_apply_stability_fixes,
)
from .workflow_tools import (
    GenerateModelingPlanInput,
    RunWorkflowFromPromptInput,
    openfoam_generate_modeling_plan,
    openfoam_run_workflow_from_prompt,
)

__all__ = [
    # Input models
    "ListTemplatesInput",
    "GetTemplateInfoInput",
    "CreateCaseInput",
    "ValidateCaseInput",
    "RunSolverInput",
    "GetRunStatusInput",
    "AnalyzeProblemInput",
    "GenerateMeshInput",
    "GenerateBoundaryConditionsInput",
    "RunParallelInput",
    "GenerateResidualPlotInput",
    "CalculateYplusInput",
    "SearchTutorialsInput",
    "ReadTutorialFileInput",
    "GetPatchListInput",
    "ReadDictionaryInput",
    "UpdateDictionaryInput",
    "PreflightCheckInput",
    "AssessCaseStabilityInput",
    "ApplyStabilityFixesInput",
    "GenerateModelingPlanInput",
    "RunWorkflowFromPromptInput",
    "ResponseFormat",
    # Tool functions
    "openfoam_list_templates",
    "openfoam_get_template_info",
    "openfoam_create_case",
    "openfoam_validate_case",
    "openfoam_run_solver",
    "openfoam_analyze_problem",
    "openfoam_get_fluid_properties",
    "openfoam_generate_mesh",
    "openfoam_generate_boundary_conditions",
    "openfoam_get_run_status",
    "openfoam_run_parallel",
    "openfoam_generate_residual_plot",
    "openfoam_calculate_yplus",
    "openfoam_search_tutorials",
    "openfoam_read_tutorial_file",
    "openfoam_get_patch_list",
    "openfoam_read_dictionary",
    "openfoam_update_dictionary",
    "openfoam_preflight_check",
    "openfoam_assess_case_stability",
    "openfoam_apply_stability_fixes",
    "openfoam_generate_modeling_plan",
    "openfoam_run_workflow_from_prompt",
]
